/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainForm;

import Connection.konek;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public final class DataPemasok extends javax.swing.JFrame {

    /**
     * Creates new form DataPemasok
     */
    
    ResultSet rs;
    Statement st;
    
    private DefaultTableModel tabmode;
    
    public DataPemasok() {
        initComponents();
        ImageIcon ico = new ImageIcon("src/Images/s2mspeed.png");
        setIconImage(ico.getImage());
        this.setLocationRelativeTo(null);
        autokdpemasok();
        non_aktif();
        tblpemasok();
        tblpemasok.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblpemasok.getTableHeader().setOpaque(false);
        tblpemasok.getTableHeader().setBackground(new Color(0,153,153));
        tblpemasok.getTableHeader().setForeground(new Color(255,255,255));
        tblpemasok.setRowHeight(25);
    }
    
    public void tblpemasok(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("Kode Pemasok");
        tbl.addColumn("Nama Pemasok");
        tbl.addColumn("Alamat");
        tbl.addColumn("E-Mail");
        tbl.addColumn("No.Telp");
        tblpemasok.setModel(tbl);
        try{
            Statement Statement=(Statement)konek.koneksiDb().createStatement();
            ResultSet res = Statement.executeQuery("select * from tb_pemasok");
            while (res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("kd_pemasok"),
                    res.getString("nm_pemasok"),
                    res.getString("alamat"),
                    res.getString("email"),
                    res.getString("no_telp")
                });
             tblpemasok.setModel(tbl);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane, "salah");
        }
    }
    
    private void non_aktif() {
        txkd.setEnabled(false);
        txnama.setEnabled(false);
        txalamat.setEnabled(false);
        txemail.setEnabled(false);
        txtelepon.setEnabled(false);
    }
    
    private void aktif() {
        //txkd.setEnabled(true);
        txalamat.setEnabled(true);
        txemail.setEnabled(true);
        txnama.setEnabled(true);
        txtelepon.setEnabled(true);
        txkd.requestFocus();
    }
    
     private void kosong() {
        txalamat.setText("");
        txemail.setText("");
        txnama.setText("");
        txtelepon.setText("");
        tambah.setEnabled(true);
        update.setEnabled(true);
        hapus.setEnabled(true);
    }
     
    private void autokdpemasok() {
        try {
            Connection c = konek.koneksiDb();
            Statement s = c.createStatement();

           String sql = "SELECT * FROM tb_pemasok ORDER by kd_pemasok desc";
            try (ResultSet r = s.executeQuery(sql)) {
                if (r.next()){
                    String kd = r.getString("kd_pemasok").substring(2);
                    String AN = ""+ (Integer.parseInt(kd) + 1);
                    String Nol = "";
                    
                    switch (AN.length()) {
                        case 1:
                            Nol = "00";
                            break;
                        case 2:
                            Nol = "0";
                            break;
                        case 3:
                            Nol = "";
                            break;
                        default:
                            break;
                    }
                    txkd.setText("SP" + Nol + AN);
                } else {
                    txkd.setText("SP001");  
                }
            }
        } catch (SQLException | NumberFormatException e) {
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txkd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txalamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtelepon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpemasok = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        update = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Pemasok Barang Sparepart");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1381, 776));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1381, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s2mspeed.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 40, 100));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA PEMASOK BARANG");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(1381, 76));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KODE PEMASOK");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA PEMASOK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ALAMAT");

        txalamat.setColumns(20);
        txalamat.setRows(5);
        jScrollPane1.setViewportView(txalamat);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMAIL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NO TELEPON");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txkd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txemail)
                            .addComponent(txtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txkd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 90, -1, 300));

        tblpemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpemasokMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpemasok);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 750, 520));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gtk-save-as.png"))); // NOI18N
        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel4.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, 30));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gtk-edit.png"))); // NOI18N
        update.setText("EDIT");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel4.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 101, 30));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/document_delete.png"))); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel4.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, 30));

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit_20px.png"))); // NOI18N
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel4.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, 30));

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel.png"))); // NOI18N
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel4.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, 30));
        jPanel4.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 47, 152, -1));

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_20px.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel4.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 43, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblpemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpemasokMouseClicked
        update.setEnabled(true);
        update.setText("EDIT");
        hapus.setEnabled(true);
        txkd.setEnabled(false);
        int i = tblpemasok.getSelectedRow();
        if (i == -1){
            return;

        }
        String kd_pemasok = (String) tblpemasok.getValueAt(i, 0);
        txkd.setText(kd_pemasok);
        String no_faktur = (String) tblpemasok.getValueAt(i, 1);
        txnama.setText(no_faktur);
        String alamat = (String) tblpemasok.getValueAt(i, 2);
        txalamat.setText(alamat);
        String email = (String) tblpemasok.getValueAt(i, 3);
        txemail.setText(email);
        String no_telp = (String) tblpemasok.getValueAt(i, 4);
        txtelepon.setText(no_telp);
    }//GEN-LAST:event_tblpemasokMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
                
        String tombol = tambah.getText();
        String kd_pemasok  = txkd.getText(); 
        String nm_pemasok  = txnama.getText();
        String alamat  = txalamat.getText();
        String email = txemail.getText();
        String no_telp = txtelepon.getText();
               
        if (tombol.equals("TAMBAH")) {
            aktif();
            kosong();
            tambah.setText("SIMPAN");
            update.setEnabled(false);
            hapus.setEnabled(false);
            }else {
            JOptionPane.showConfirmDialog(null, "Apakah Data anda sudah benar?", "INFORMASI",JOptionPane.YES_NO_OPTION);
                        try {
                            Connection c = konek.koneksiDb();
                            String sql = "INSERT INTO tb_pemasok VALUES (?, ?, ?, ?, ?)";
                try (PreparedStatement p= c.prepareStatement(sql)) {
                    p.setString(1, kd_pemasok);
                    p.setString(2, nm_pemasok);
                    p.setString(3, alamat);
                    p.setString(4, email);
                    p.setString(5, no_telp);
                    p.executeUpdate();
                }
                            txkd.requestFocus();
                            } catch (SQLException e) {
                            System.out.println("Terjadi Error");
                            }finally{
                                String   msg="<html>Kode Pemasok         = " +txkd.getText()+" <br>"
                                + "Nama Pemasok        = " +txnama.getText()+"<br>"
                                + "Alamat              = " +txalamat.getText()+"<br>"
                                + "Email              = " +txemail.getText()+"<br>"
                                + "No.Telp             = " +txtelepon.getText()+"<html>";
                                JOptionPane optionPane=new JOptionPane();
                                optionPane.setMessage(msg);
                                optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                                JDialog dialog=optionPane.createDialog(null, "DATA DISIMPAN");
                                dialog.setVisible(true);
                            }
                            new DataPemasok().setVisible(true);
                            this.dispose();
                            autokdpemasok();
                            tblpemasok();
                            tambah.setText("TAMBAH");
                            non_aktif();
            }
    }//GEN-LAST:event_tambahActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        String kd_pemasok  = txkd.getText(); 
        String nm_pemasok  = txnama.getText();
        String alamat  = txalamat.getText();
        String email = txemail.getText();
        String no_telp = txtelepon.getText();
        
        if ("EDIT".equals(update.getText())) {
            aktif();
            update.setText("UPDATE");
            hapus.setEnabled(false);
            tambah.setEnabled(false);
        } else {
                int ok = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Ubah Data Ini?", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
            try (Statement Statement = (Statement)konek.koneksiDb().createStatement()) {
                    Statement.executeUpdate("Update tb_pemasok SET kd_pemasok='"+ kd_pemasok +"',"
                    + "nm_pemasok ='"+ nm_pemasok +"',alamat ='"+ alamat +"',email='"+email +"',"
                    + "no_telp ='"+ no_telp +"' where kd_pemasok='"+kd_pemasok+"'");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Data Pemasok Gagal Di Update" + e);
                }
            kosong();
            autokdpemasok();
            JOptionPane.showMessageDialog(null, "Data Pemasok berhasil Di Update");
            update.setText("EDIT");
            tblpemasok();
            }
    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed

        String kd_pemasok = txkd.getText();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ingin Menghapus Data Ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            try {
                Statement Statement =(Statement)konek.koneksiDb().createStatement();
                Statement.executeUpdate(" Delete from tb_pemasok where kd_pemasok=('" +  kd_pemasok + "');");
                kosong();
                JOptionPane.showMessageDialog(null, "Data Pemasok Berhasil Dihapus");
                autokdpemasok();
                txkd.requestFocus();
                tblpemasok();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Pemasok Gagal Di Hapus" + e);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
        FormUtamaPartman fup = new FormUtamaPartman();
        fup.show();
    }//GEN-LAST:event_keluarActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        kosong();
        tambah.setText("TAMBAH");
        non_aktif();
    }//GEN-LAST:event_batalActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String tombol = btnCari.getText();
        if (tombol.equals("Cari")){
            Object[] Baris = {"Kode Pemasok", "Nama Pemasok", "Alamat", "E-Mail", "No.Telp"};
            tabmode = new DefaultTableModel(null, Baris);
            tblpemasok.setModel(tabmode);
            String sql = "Select * from tb_pemasok where kd_kendaraan like '%" + txtCari.getText() + "%'" +
            "or nm_pemasok like '%" + txtCari.getText() + "%'";
            try {
                Statement stat = konek.koneksiDb().createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()) {
                    String kd_pemasok = hasil.getString("kd_pemasok");
                    String nm_pemasok = hasil.getString("nm_pemasok");
                    String alamat = hasil.getString("alamat");
                    String email = hasil.getString("email");
                    String no_telp = hasil.getString("no_telp");
                    String[] data = {kd_pemasok,nm_pemasok,alamat,email,no_telp};
                    tabmode.addRow(data);
                }
            } catch (Exception e) {
            }
            btnCari.setText("Batal");
        }else{
            tblpemasok();
            btnCari.setText("Cari");
            txtCari.setText("");
            tambah.setEnabled(true);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DataPemasok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton keluar;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tblpemasok;
    private javax.swing.JTextArea txalamat;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txkd;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtelepon;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
