/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainForm;

import Connection.konek;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class TambahStokSparepart extends javax.swing.JFrame {

    /**
     * Creates new form TambahStokSparepart
     */
    public TambahStokSparepart() {
        initComponents();
        ImageIcon ico = new ImageIcon("src/Images/s2mspeed.png");
        setIconImage(ico.getImage());
        this.setLocationRelativeTo(null);
        waktu();
        non_aktif();
        barangmasuk();
        tblsparepart();
        tblsparepart.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblsparepart.getTableHeader().setOpaque(false);
        tblsparepart.getTableHeader().setBackground(new Color(0,153,153));
        tblsparepart.getTableHeader().setForeground(new Color(255,255,255));
        tblsparepart.setRowHeight(25);
    }
    
    public void waktu(){
        Date fs=new Date();tanggalmasuk.setDate(fs);
    }
    
    public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "Masukan Angka!", "WARNING", JOptionPane.WARNING_MESSAGE);
       }
    }
    
    private void non_aktif() {
        kdbarang.setEnabled(false);
        barangmasuk.setEnabled(false);
        stokawal.setEnabled(false);
        tbstok.setEnabled(false);
        tanggalmasuk.setEnabled(false);
    }
    
    private void aktif() {
        kdbarang.setEnabled(true);
        barangmasuk.setEnabled(true);
        stokawal.setEnabled(true);
        tbstok.setEnabled(true);
        tanggalmasuk.setEnabled(true);
        kdbarang.requestFocus();
    }
    
     private void kosong() {
        kdbarang.setText("");
        barangmasuk.setSelectedItem("");
        stokawal.setText("");
        tbstok.setText("");
        tambah.setEnabled(true);
    }
    
    private void barangmasuk() {
          
        try {
            Connection c = konek.koneksiDb();
            Statement s = c.createStatement();

            String sql = "SELECT nm_sparepart FROM tb_sparepart WHERE stk !=''";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                barangmasuk.addItem(r.getString("nm_sparepart"));
            }

            r.last();
            int jumlahdata = r.getRow();
            r.first();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
     
    public void tblsparepart(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("Kode Sparepart");
        tbl.addColumn("Nama Sparepart");
        tbl.addColumn("Merk");
        tbl.addColumn("Harga");
        tbl.addColumn("Stock");
        tblsparepart.setModel(tbl);
        try{
            Statement Statement=(Statement)konek.koneksiDb().createStatement();
            ResultSet res = Statement.executeQuery("select * from tb_sparepart");
            while (res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("kd_sparepart"),
                    res.getString("nm_sparepart"),
                    res.getString("merk"),
                    res.getString("harga"),
                    res.getString("stk")
                });
             tblsparepart.setModel(tbl);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane, "salah");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kdbarang = new javax.swing.JTextField();
        stokawal = new javax.swing.JTextField();
        tbstok = new javax.swing.JTextField();
        tanggalmasuk = new com.toedter.calendar.JDateChooser();
        barangmasuk = new javax.swing.JComboBox<>();
        tambah = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsparepart = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaksi Pemesanan Sparepart");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1381, 776));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1381, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s2mspeed.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 10, 100));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TAMBAH STOK SPAREPART");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 350, 40));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        kdbarang.setEditable(false);
        kdbarang.setBackground(new java.awt.Color(255, 255, 255));
        kdbarang.setForeground(new java.awt.Color(162, 162, 162));
        kdbarang.setText("Kode Sparepart");
        kdbarang.setBorder(null);
        kdbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kdbarangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kdbarangFocusLost(evt);
            }
        });

        stokawal.setEditable(false);
        stokawal.setBackground(new java.awt.Color(255, 255, 255));
        stokawal.setForeground(new java.awt.Color(162, 162, 162));
        stokawal.setText("Stok Awal");
        stokawal.setBorder(null);

        tbstok.setForeground(new java.awt.Color(162, 162, 162));
        tbstok.setText("Tambah Stok");
        tbstok.setBorder(null);
        tbstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbstokActionPerformed(evt);
            }
        });
        tbstok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbstokFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbstokFocusLost(evt);
            }
        });
        tbstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbstokKeyTyped(evt);
            }
        });

        barangmasuk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Nama Sparepart -" }));
        barangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangmasukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barangmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokawal, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbstok, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(barangmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(kdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(stokawal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(tbstok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gtk-save-as.png"))); // NOI18N
        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit_20px.png"))); // NOI18N
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel.png"))); // NOI18N
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        tblsparepart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblsparepart);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah)
                            .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 164, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kdbarangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdbarangFocusLost

    }//GEN-LAST:event_kdbarangFocusLost

    private void tbstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbstokActionPerformed

    private void tbstokFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbstokFocusGained
        if(tbstok.getText().trim().toLowerCase().equals("tambah stok")){
            tbstok.setText("");
            tbstok.setForeground(Color.BLACK);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_tbstokFocusGained

    private void tbstokFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbstokFocusLost
        if(tbstok.getText().trim().equals("")|| tbstok.getText().trim().toLowerCase().equals("tambah stok")){
            tbstok.setText("Tambah Stok");
            tbstok.setForeground(new Color(162,162,162));
        } // TODO add your handling code here:
    }//GEN-LAST:event_tbstokFocusLost

    private void tbstokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbstokKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tbstokKeyTyped

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
        FormUtamaPartman fup = new FormUtamaPartman();
        fup.show();
    }//GEN-LAST:event_keluarActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        kosong();
        tambah.setText("TAMBAH");
        non_aktif();
    }//GEN-LAST:event_batalActionPerformed

    private void kdbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_kdbarangFocusGained

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat dformat=new SimpleDateFormat("yyyy-MM-dd");
        String tombol = tambah.getText();
        Object nm_sparepart  = barangmasuk.getSelectedItem();
        String kd_sparepartmsk = kdbarang.getText();
        String tambahstk = tbstok.getText();
        String tglmasuk = dformat.format(tanggalmasuk.getDate());
        
        if (tombol.equals("TAMBAH")) {
            aktif();
            //kosong();
            tambah.setText("SIMPAN");
            }else {
            JOptionPane.showConfirmDialog(null, "Apakah Data anda sudah benar?", "INFORMASI",JOptionPane.YES_NO_OPTION);
                        try {
                            Connection c = konek.koneksiDb();
                            String sql = "INSERT INTO tb_sparepartmasuk VALUES (?, ?, ?, ?, ?)";
                            PreparedStatement p = c.prepareStatement(sql);
                            p.setString(1, null);
                            p.setString(2, (String) nm_sparepart);
                            p.setString(3, kd_sparepartmsk);
                            p.setString(4, tambahstk);
                            p.setString(5, tglmasuk);
                            p.executeUpdate();
                            p.close();
                            kdbarang.requestFocus();
                            } catch (SQLException e) {
                            System.out.println("Terjadi Error");
                            }finally{
                                String   msg="<html>Nama Sparepart         = " +barangmasuk.getSelectedItem()+" <br>"
                                + "Kode Sparepart        = " +kdbarang.getText()+"<br>"
                                + "Stok              = " +tbstok.getText()+"<br>"
                                + "Tanggal Masuk             = " +tanggalmasuk.getDate()+"<html>";
                                JOptionPane optionPane=new JOptionPane();
                                optionPane.setMessage(msg);
                                optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                                JDialog dialog=optionPane.createDialog(null, "DATA DISIMPAN");
                                dialog.setVisible(true);
                                new TambahStokSparepart().setVisible(true);
                            this.dispose();
                            tblsparepart();
                            tambah.setText("TAMBAH");
                            non_aktif();
                            }
                            
            }
    }//GEN-LAST:event_tambahActionPerformed

    private void barangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangmasukActionPerformed
        if (barangmasuk.getSelectedItem().equals("- Nama Sparepart -")){
            kdbarang.setText("");
        }else{
            try {
                Connection c = konek.koneksiDb();
                Statement s = c.createStatement();

                String sql = "SELECT kd_sparepart, stk, harga FROM tb_sparepart WHERE nm_sparepart ='" + barangmasuk.getSelectedItem() + "'";
                ResultSet r = s.executeQuery(sql);

                while (r.next()) {
                    kdbarang.setText(r.getString("kd_sparepart"));
                    kdbarang.setForeground(Color.BLACK);
                    stokawal.setText(r.getString("stk"));
                    stokawal.setForeground(Color.BLACK);

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }       // TODO add your handling code here:
    }//GEN-LAST:event_barangmasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahStokSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahStokSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahStokSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahStokSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahStokSparepart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> barangmasuk;
    private javax.swing.JButton batal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField kdbarang;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField stokawal;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tanggalmasuk;
    private javax.swing.JTable tblsparepart;
    private javax.swing.JTextField tbstok;
    // End of variables declaration//GEN-END:variables
}
